* Quicklisp Doctor

I need the possibility to have a program that examines the quicklisp installation.

** Project goals
The following goals have been implemented to some extent.

+ Information about new quicklisp release
+ List of local-projects
+ Git version of local-projects
+ SBCL specific
+ Works on Windows too

We may need to improve the code some more. The next step would be a list of
requirements that could be used to make sure we have the correct commits in
local-projects.

Windows version works with Msys2 installed and may not work in all situations.
That may require more work. If you have any suggestions please raise an issue.

** Automatically checking commits
We can run a simple function to check if our local projects are up to date.

#+begin_src lisp
  (ql:quickload 'quicklisp-doctor)
  (quicklisp-doctor:examine-local-projects
   '(("cl-confidence" "commit 14dc40a0fde822f4aab4fefc9b40ef5fdcbcd666")
     ("dot-cons-tree" "commit 529dc869e6e46535f4d5567658d750068e55bd5b")))

  ;; (("cl-confidence" :MATCHING-COMMIT) ("dot-cons-tree" :MATCHING-COMMIT))
#+end_src
